# Generated by Django 3.0.8 on 2020-08-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(default='lakufirma', max_length=50)),
                ('contactname', models.CharField(default='tommi', max_length=50)),
                ('address', models.CharField(default='trueflasecdo 3', max_length=100)),
                ('phone', models.CharField(default='437483434', max_length=20)),
                ('email', models.CharField(default='vfgvvgfgfdv', max_length=50)),
                ('country', models.CharField(default='vdfvvbg', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='laku', max_length=20)),
                ('packagesize', models.CharField(default=3, max_length=20)),
                ('unitprice', models.IntegerField(default=3)),
                ('unitsinstock', models.IntegerField(default=3)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productsapp.Supplier')),
            ],
        ),
    ]
