# Generated by Django 3.0.8 on 2020-08-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
    ]
